README.md
The screenshot link in the README is currently broken. By using the magic of relative paths, we make sure that the screenshots in the README stay up to date and visible, as long as they stay in the same directory.
=> Fix screenshot in README

README.md
Fixed the abbrevation of android ndk (native development kit) from nkd
=> Fixed typo: ndk from nkd

project/env.json.example, project/src/index.html, project/src/js/http.js, project/www/lib/socketWorker.js, tarifa.json
lichess.org is now using TLS \o/. The old API and socket endpoints will be available as long as we need them, but let's switch as soon as possible. This has been changed:
* http:// -> https://
* ws://socket.{lang}.lichess.org -> wss://socket.lichess.org
* Alternative ports 9025, 9026, 9027, 9028, 9029 now accept secure websockets
In this PR the protocol is now included in env.json, so you could still configure http:// for local testing. Every developer will have to update their env.json, though.
Tested:
=> Switch to HTTPS

project/src/js/settings.js, project/src/js/ui/otb/actions.js, project/src/js/ui/otb/otbCtrl.js, project/src/js/ui/otb/otbView.js, project/src/styl/chessground-board.styl, project/src/styl/chessground.styl
This is a fix for issue #273 
It requires another pull on the chessground repository (https://github.com/veloce/chessground-mobile/pull/1)
In order to not mess with the surrounding layout and keep maximum board space, coordinates are inside the squares.
ISSUE:
The board is not updated with `m.redraw` but getting out of OTB and in again does the trick.
=> Fix for issue #273

src/index.html, src/js/ui/analyse/explorer/explorerCtrl.ts, src/js/ui/analyse/explorer/explorerView.tsx, src/js/ui/analyse/explorer/explorerXhr.ts
There's a new tablebase endpoint.
Changes:
* Moved to new server that has space for variant tablebases in the future
* Start querying the 6 man tablebases when there are 7 pieces on the board to display winning transitions
* API sends less unused information, `real_wdl` -> `wdl`
We can keep the old endpoint up as long as we like.
=> Update tablebase endpoint

src/js/ui/players/playerXhr.ts
The `friend` flag is a neat option that @ornicar showed me. It's a nice way to prioritize what most users are doing most of the time (searching for a friend), but still pulling up other results when the user enters a prefix that doesn't match any of their friends.
=> Return only friends from search until no friends match. Then search everyone.

config.xml, deepLinkTest.html, src/deepLinks.ts
Opening a link like `lichess.org/analysis/1k6/1r6/2K5/Q7/8/8/8/8_w_-_-` or `lichess.org/editor/1k6/1r6/2K5/Q7/8/8/8/8_w_-_-` in the app will open the lichess.org web page in the in-app browser.
This PR enables such links to open the mobile app pages instead.
=> Handle position deep links

src/ui/analyse/explorer/ExplorerCtrl.ts
Similar to ornicar/lila@30385b6c41a335d521a647eef78801ffd2336fde from https://github.com/ornicar/lila/pull/3797: Loading also on leading edges makes the explorer feel much faster while bursts of requests are still prevented.
=> Load opening explorer info on leading edge

config.xml, src/index.html, src/ui/analyse/explorer/explorerXhr.ts
They are on a cookieless domain now.
=> Update explorer and tablebase endpoints

src/styl/analyse.styl
The same way it is done on the desktop.
Before:
After:
=> Highlight current move in ongoing game analysis

src/ui/training/TrainingCtrl.ts
Without this, offline puzzles were always shown from white's perspective when moving to the analysis board.
=> Make puzzle orientation explicit

src/lichess/interfaces/game.ts, src/ui/shared/round/OnlineRound.ts, src/ui/shared/round/view/button.tsx
After successfully toggling the bookmark in the server, there is no need for a separate request to update the gamedata just to toggle the UI. This is the way it is already done in the search and game list views.
Also, there seems to be some problem in the server - it takes some time for it to start returning "bookmarked = true"  in the gameData.  This causes the UI to not toggle at all, this PR works around this issue.
=> Change the bookmark icon to change locally in round view

config.xml
A pain point for me and (I suspect) others with the app is that sometimes the piece movement volume is too loud or too soft, but using the volume keys defaults to adjusting the ring volume. This PR changes the default volume controlled by the hardware keys to instead be the media volume.
=> Make hardware keys control media by default

config.xml, package.json
Upgrade `cordova-plugin-crosswalk-webview` package to `2.3.0` to `2.4.0` in order to take advantage of this fix for Cordova 7.0 (https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/commit/e58176139cab79bfc2351436acd35664348fff6c)
=> Upgrade webview to fix build errors

src/ui/shared/round/OnlineRound.ts
Previously, chessground was not updated for the en passant move before trying to explode the pieces (but, per the rules of atomic, not pawns) around the capturing pawn. This meant that `chessgroundCtrl.state.pieces[k]` in this line (https://github.com/veloce/lichobile/blob/master/src/ui/shared/round/atomic.ts#L14) always returned false because the pawn hadn't yet reached its destination square.
This PR simply moves the atomic explosion code so that it is processed after the move is processed. I've tested this and it fixes the issue.
Closes: https://github.com/veloce/lichobile/issues/884
=> Fix En Passant in Atomic

src/ui/analyse/view/actionsView.tsx
Reverse when expand and compress buttons are shown below analysis board to make their purpose clearer.
=> Reverse when expand and compress buttons are shown

src/ui/analyse/charts/acpl.ts
This does not address the fact that `xply` can be negative and when used to index into `graphData` results in `undefined`
Closes https://github.com/veloce/lichobile/issues/935
=> Fix off-by-one error when first ply in 'treeParts' is not 0

src/styl/analyse.styl, src/styl/board-content.styl
Reapply patch that @veloce originally wrote to fix the analysis scrolling bug, which has reappeared in Chrome 74.
=> Fix analysis scrolling

src/ui/training/TrainingCtrl.ts, src/ui/training/database.ts, src/ui/training/trainingView.ts
Related issues https://github.com/veloce/lichobile/issues/876 and https://github.com/ornicar/lila/issues/4409
The synchronization  problem between the puzzles between the website and the app is that the app maintains an offline cache of puzzles. 
The solution I propose is not the most elegant, but after so many months of suffering the incidence, I think it's worth it until we get something better. It tries to add a button to invalidate the local cache and re-request a new batch of puzzles to the server.
You can see the new "resync" button to the right of the analysis button:
=> issue #876: workaround - new button to resync puzzles

src/ui/user/userView.tsx
If `avail` is false don't make the rating clickable.
Also factored out to the `div` properties into `prop` to make the code slightly easier to read.
Closes https://github.com/veloce/lichobile/issues/952
=> Make perfRatings with no seperate pages unclickable

package-lock.json, package.json
Discovered a vulnerability with `npm audit` in Gulp v2.0.0. Upgraded to 3.0.2 and tested via `npm run build`, `npm run build-stage`, and `npm watch`.
=> Upgrade gulp-preprocess to 3.0.2

config.xml, package-lock.json, package.json
Upgraded `cordova-plugin-stockfish` to the most recent commit (https://github.com/veloce/cordova-plugin-stockfish/commit/7cc6722888bf482584205ca753c288826786c73b) to fix the Android NDK build issues. See https://github.com/veloce/cordova-plugin-stockfish/pull/14.
=> Upgrade Stockfish plugin to fix build issues

src/session.ts
Fix 'bad request' error when updating game behavior settings by submitting 'moretime' field.
Resolves https://github.com/veloce/lichobile/issues/1020
=> Add `moretime` field to settings update request sent to server

config.xml
This comment (https://github.com/apache/cordova-plugin-splashscreen/pull/225#issuecomment-516405842) suggested a fix to the back button issue that was raised here (https://github.com/veloce/lichobile/issues/1009) and here (https://github.com/veloce/lichobile/issues/985)
I've implemented the suggested fix and it works. I confirmed the issue existed on my phone and disappeared once I added the extra parameter to the `<widget>` tag.
=> Fix back button on Android

src/ui/analyse/ceval/StockfishEngine.ts
Fix the display of Stockfish's analysis when multiple analysis lines
are used (MultiPV > 1).  There are two situations where this is broken:
1. The position has fewer legal moves than the requested MultiPV.
(Stockfish only emits one line for each legal move, even if the MultiPV
option is higher than that.)
2. The user does some analysis with a high MultiPV, and then sets it to
a lower value.  (We have no mechanism to reset expectedPvs to a lower
value, it can only ever increase.)
In either case, we will not receive a multipv value equal to
expectedPvs.  This means that we never emit the analysis received from
Stockfish inside StockfishEngine.processOutput.  This manifests in the
UI as an hourglass in the Stockfish section of the Analysis board, and
the hourglass never goes away, even when …
=> Fix display of Stockfish analysis with multiple lines.

src/ui/newGameForm.ts
I was not able to test this because I couldn't get `npm run watch` to run on the new capacitor branch without errors, but this seems like a pretty harmless edit that addresses https://github.com/veloce/lichobile/issues/1053
=> Conform naming of 'Quick Pairing' and utilize new translations

src/lichess/variant.ts
The first-time alert for the Horde variant had white's and black's variant goals reversed.
=> Correct the horde alert

src/ui/shared/round/view/roundView.tsx
answerRequired should be false if the reason for answerRequired is a draw offer or takeback request and the game is already over.
This is just a surface level fix for issue #1060 , I thought about setting proposingTakeback and offeringDraw to false when the game ends, but I don't know how to go about that and what possible side-effects could be caused by that.
=> fixed #1060

src/styl/new-game.styl, src/xhr.ts
Issue: The bottom row is shorter for the new 3x4 grid
Solution: Just specify that the grid has three columns, but don't specify the number of row. This gracefully handles both the new 3x4 grid
...and the old 3x3 grid.
My dev machine downloaded the new 3x4 grid and presumably people's phones will do the same as their caches expire (I think) so would be good to make this CSS change now so the UI can gracefully handle the switchover from 3x3 to 3x4.
=> Change CSS to accomodate new 3x4 grid (vs. old 3x3 grid)

src/ui/shared/clock/clockSet.ts
This should fix issue #1212 where sound effects aren't playing for many modes.
=> Reenabled sound effects for other clock modes. Fix for issue#1212

src/ui/otb/otbView.tsx
This PR should fix the issue reported in #1214. It does so by stopping the OTB clock from ticking when the user taps and opens the 'newGameMenu'.
=> Fix for premature flagging for OTB clock.

src/ui/user/perfStats/variantPerfView.tsx
Ref. https://github.com/veloce/lichobile/issues/1074
I've changed `variantPrefView.tsx` to show playing streak from date instead of last game played date. See referenced issue for more details.
=> fix(user profile): playing streak date

src/ui/user/perfStats/variantPerfView.tsx
Fill in missing dates in the ratings graph with the previous rating. Implemented in lila here: https://github.com/ornicar/lila/pull/6902
In [the original issue](https://github.com/ornicar/lila/issues/6743):
> To add, I'd say that if my rating on January 1 is 2000 and I don't play until May 5, when I drop 50 points to 1950, I would expect the graph to be a straight line at 2000 from January 1 till May 4, and then a one-day steep drop to 1950. As that's what happened: my rating was still 2000 on May 4, and dropped to 1950 on May 5.
> 
> (Right now the plot would draw a straight line from 2000 on January 1 to 1950 on May 5, as if I gradually lost my rating over time. It's incorrect and inelegant.)
Tested in REPL:
```
> example
[
{ date: 2020-05-15T07:00:00.000Z, rating: 1500 },
{ date: …
```
=> Fill in missing dates in ratings graph

scripts/i18n-update.ts
Set maxBuffer to 10MB when executing unzip to avoid errors encountered when default 1MB used
Found a similar issue and fix here: https://github.com/nicojs/node-install-local/issues/8
=> Set unzip maxBuffer to 10MB 

src/styl/tournament.styl
Conform to Lila: https://github.com/ornicar/lila/blob/master/ui/tournamentSchedule/css/_schedule.scss#L96
Closes https://github.com/veloce/lichobile/issues/1362
=> Add color for eastern tournaments to conform to Lila

src/ui/tournament/detail/playerInfo.tsx
By using `pairings.length` instead of `player.nb.game`, we include partially completed games and avoid the situation where the first game is numbered 0.
Closes https://github.com/veloce/lichobile/issues/1352
=> Count based on game array length

android/app/build.gradle
Make the Android "withoutNNUE" flavor the default which makes building simpler and is probably what newcomers to the project want.
I tried it out, and after this fix "withoutNNUDebug" was selected when I created a new Android Studio project:
=> Use withoutNNUE flavor by default

src/announce.ts, src/i18n.ts, src/session.ts, src/socket.ts, src/styl/main.styl, src/ui/announceView.ts, src/ui/layout.ts, src/ui/shared/layout/MainBoard.ts
Part of https://github.com/veloce/lichobile/issues/1539 .
This does not include:
- real-time `announce` message handling on websockets
- announcements for logged-out users
but hopefully this sets up a good foundation for those things later.
Note that this only affects "free" layouts - so e.g. online rounds and analysis layouts don't show any announcements. Is this desirable?
=> Show announcements

src/i18n.ts, src/styl/games-menu.styl, src/ui/gamesMenu.ts
To remove `toATypeGame` i18n key, as mentioned in https://github.com/veloce/lichobile/pull/1601#discussion_r598081391. Ordering (time - variant - rating mode) is consistent with the quick-pairing overlay:
=> Tweak challenge card

src/styl/chessground-piece.styl
The entire offline play table was rotated 180, but the icons inside were also flipped 180. Removed the latter style to close #1617.
Tested the following modes with advantages on each side:
- offline vs. AI
- OTB with "flip pieces and opponent info after move" enabled
- OTB without the above setting enabled
=> Fix OTB advantage icon orientation

src/settings.ts, src/styl/board-content.styl, src/ui/settings/gameDisplay.ts, src/ui/shared/layout/MainBoard.ts, translation/source/mobile-misc.yaml, www/i18n/en-US.js
Closes #1353. Closes #1541.
The setting:
Offline round:
Analysis:
Online round:
=> Option to choose board side in landscape mode

src/ui/training/TrainingCtrl.ts, src/ui/training/trainingView.ts
Closes #1650. I imagine the TrainingCtrl was being reused, so its piece theme wasn't getting updated. This is more similar to how the Board view gets the piece theme (it's considered part of the view state, not the controller state).
=> Get training ctrl piece theme directly from settings

src/chessground/util.ts, src/ui/analyse/view/boardView.ts
Closes #1676.
Tested with a local client against [the game mentioned](https://lichess.org/9sVANEDz/black#79) in the issue.
I also tried to test against a [random bughouse game](https://lichess.org/Jf7wjgRf/black#19) to verify drop move suggestions are rendered as expected. However, it appears the server doesn't provide best move suggestions for drops, which is when this code path would be exercised.
=> Fix piece color for past best move when promo

android/app/src/main/AndroidManifest.xml
This fixes black bars visible at the top and bottom of the screen on some devices (like Samsung S8, etc.), as mentioned in #1145 and #1416.
If the `android:resizeableActivity` flag was set to `false` on purpose for some reason, we can also set the [minimum aspect ratio](https://developer.android.com/guide/practices/screens-distribution#MaxAspectRatio) instead to 2.1.
Also, the `android:resizeableActivity` flag can be removed altogether now, as it is true by default.
=> Fix black bars visible on Android devices with narrow aspect ratios

src/ui/coordinates/CoordCtrl.ts, src/ui/coordinates/coordView.ts
In order to align behavior with the website, I changed the coordinates training such that the board orientation already changes on selecting a color, even before training is started. 
This also means a random color is automatically selected on tap and on initialization.
Also color selection is prevented when training is in progress.
=> Update board orientation on color selection

src/styl/chessground.styl
We prepend the board theme name with `board-` when constructing class names for the board element. Closes #1752.
=> Fix last-move theme special casing

src/ui/analyse/view/boardView.ts
Closes #1759. Note the username and score (1, 0, ½) are not included for anonymous players.
Verified locally that time data for any game is available to both registered and unregistered/guest/anonymous users, i.e. the analysis board will look the same for both.
https://user-images.githubusercontent.com/569991/125720491-aa64eaf9-ecff-4e63-afc2-6613dd1d6a12.mov
=> Restore time indicator for anonymous analysis

src/ui/shared/round/OnlineRound.ts
Currently, the user can navigate back to the game round view from a _playable_ game by pressing the back arrow or the native back button; however, from a _non-playable_ game, the only way to do the same is via the back arrow. Both states should allow the use of the native back button to navigate back.
This `replace` parameter looks left over from a WIP commit from 2 years ago, so do correct me if I'm missing some more context here 🙂 
Closes #1758.
=> Push instead of replace path when going to analysis

src/lichess/interfaces/challenge.ts, src/ui/gamesMenu.ts
Closes #1800.
Challenge objects from the API [include a `speed` key](https://github.com/ornicar/lila/blob/44fd283b88f289ce5ad928229e07b3c578903949/modules/challenge/src/main/JsonView.scala#L62). Similarly to https://github.com/veloce/lichobile/issues/1724#issuecomment-861435887 , which was basically this same issue but for tournament icons, we should use that instead of the server-specified icon to choose what icon to show.
Tested locally.
=> Fix broken challenge icons

src/ui/ai/AiRound.ts, src/ui/ai/aiView.tsx, src/ui/analyse/AnalyseCtrl.ts, src/ui/otb/OtbRound.ts, src/ui/shared/offlineRound/promotion.ts, src/ui/shared/round/OnlineRound.ts, src/ui/shared/round/index.ts, src/ui/shared/round/promotion.ts, src/ui/training/TrainingCtrl.ts
Closes #1168.
https://user-images.githubusercontent.com/569991/126903790-ed249a2f-4db4-4613-a027-a8b239fbd1d1.mov
https://user-images.githubusercontent.com/569991/126903792-66f540f7-7d13-470b-89f0-a82c127b4a71.mov
https://user-images.githubusercontent.com/569991/126903793-a979fe16-47f9-496d-be10-c80862875f4c.mov
https://user-images.githubusercontent.com/569991/126903806-84f56062-6047-49b0-a67e-ecdd70412e45.mov
https://user-images.githubusercontent.com/569991/126903807-452c71c5-f3a3-4947-bcd5-38414ef20b51.mov
https://user-images.githubusercontent.com/569991/126903809-a0a438e6-d930-41f8-94fd-471b28a51d27.mov
=> Move global pawn promotion state to round control objects

src/ui/analyse/explorer/ExplorerCtrl.ts, src/ui/analyse/explorer/explorerView.tsx, src/ui/analyse/explorer/interfaces.ts, src/ui/analyse/explorer/util.ts
Replaced usage of WDL with category computed on server side,
introduce maybe-win and maybe-loss, make translations more precise.
Fixes the equivalents of the following lila issues:
* https://github.com/ornicar/lila/issues/6846
* https://github.com/ornicar/lila/issues/8684
=> Update and fix tablebase

src/ui/analyse/AnalyseCtrl.ts
Closes #1725. All currently supported variants besides horde and antichess require exactly one king on each side.
(study: https://lichess.org/study/kI8ikTU4)
=> Disable ceval for illegal FEN on analyse board

src/stockfish.ts
It seems that the web stockfish understands different variant strings than the mobile stockfish-capacitor? In my testing within the browser, it was necessary to pass different UCI_variant strings.
=> Variant mangling

src/stockfish.ts, src/ui/ai/AiRound.ts, src/ui/ai/engine.ts
Promotion piece received from engine now passed forward. This should close #1802.
In testing, it seems that the proper variant string had not been passed on. This is perhaps a separate issue, in commit 3050342.
=> Fix promotion

src/index.mustache
Attempt to fix #1859.
> Best guess: the Xiaomi / MIUI default webview has a "best effort" dark mode that attempts to invert colors. Opening a "best effort" PR for this now
I don't have a Xiaomi device so I can't confirm this fixes the issue, but it shouldn't break anything (this app is already designed for dark mode w/internal theming). If anyone seeing this PR does have a Redmi 9 and can compile + install + test this branch, I'd be very grateful.
=> Disable best-effort dark mode

src/lichess/tournament.ts, src/ui/tournament/detail/TournamentCtrl.ts, src/ui/tournament/detail/tournamentView.tsx
Discovered while investigating #1897.
- Tournament with no chat enabled was crashing locally due to an unkeyed `null` node; replaced with empty keyed fragment
- Tournaments do not require re-entering passwords to resume play from pause, updated locally to not re-require password
- Tournament join API response contains an error message, display that to the user when available
=> Tournament bug fixes and improvements

src/ui/analyse/view/boardView.ts
Closes #1874. It's possible to be looking at an anonymous game with clock info for some nodes but with no clock info for the current node. Setting the player name to `&nbsp;` will prevent the screen from shifting between nodes with and without clock info for those games.
This code affects display for all analysis situations, so I've tried to capture all possible scenarios below. The two not listed that I can think of are:
- a non-synthetic anonymous game with no time control, which I don't believe it's possible to create (just tried to do so and was told "you need an account to do that")
- a study with clock info but no player info (don't know if it's possible to have a study with clock info?)
| Situation | Picture | Notes |
| ---- | ---- | ---- |
| Non-synthetic anonymous game | …
=> Fix anonymous no-clock analysis screen shift

src/styl/home.styl
Closes #1939. Note that both before and after, a large list of correspondence seeks pushes the "create game" button out of the initial view. The user can still scroll to view the rest of the list and that button.
=> Shrink correspondence seek row height

src/lichess/interfaces/tournament.ts
I'm glad it's unused, that makes the next gen tournament server easier to build!
=> remove unused tournament.me.username

src/ui/challengeForm.ts, src/ui/newGameForm.ts, src/utils/index.ts
=> Allow choice of color for standard rated games

src/styl/main.styl
Closes #1970. As noted in the issue, the `env(safe-area-inset-top)` should apply to top padding, but not bottom.
=> Fix announcement padding on iOS

android/app/src/main/res/values/styles.xml
These aren't doing anything productive, as they're quickly overridden when
`BridgeActivity` resets the theme. Additionally `windowIsTranslucent` may trigger
this Android issue https://issuetracker.google.com/issues/194427611 , when
using 3rd party launchers that support the return to home animation on
Android 11+, the Lichess icon may get stuck on the screen.
Tested on Android 11+ with and without GestureNavContract and with and without dark mode.
Also tested on Android 8.0 to verify this doesn't introduce splash screen issues on older Android versions.
I was unable to find out why these parameters were originally added.
=> Remove unneeded Android theme parameters

ios/App/Podfile.lock, src/styl/modal.styl
Closes #1979.
Since we're using [the default `box-sizing: content-box`](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing), we don't need to adjust the height to account for the padding, which is already set to `env(safe-area-inset-top)`.
=> Fix tournament header padding on notched devices

src/styl/board-content.styl
Closes #1992. Note that the halfsize name margin is affected on **incomplete** games in both **half and full sizes.**
| Branch | Completion status | Size | Screenshot | 
| ------- | ---- | --- | --- |
| master | incomplete | 1️⃣   | https://user-images.githubusercontent.com/569991/150544244-1959c39f-006f-4726-861e-a7f6c51446c5.png |
| master | incomplete | ½ | https://user-images.githubusercontent.com/569991/150544339-1331f656-2120-4923-b5d2-0f1d57709eab.png |
| master | complete | 1️⃣  | https://user-images.githubusercontent.com/569991/150544586-a219753c-3220-4f82-ae32-acb816a32d57.png |
| master | complete | ½  | https://user-images.githubusercontent.com/569991/150544631-25ade26c-0da6-4b26-ab85-c44db0c505d8.png |
| this | incomplete | 1️⃣  | **name left margin affected** …
=> Tweak board name/result margin

src/styl/board-content.styl
Sorry @veloce , I didn't give you the proper data to fix #1869. Although the screen size is reportedly 716x720, it seems that the viewport size is just 665x716 (as reported by Chrome when doing remote debugging)
After applying this change, this is how the screen looks:
I have no idea about media queries, so I'm not exactly sure why you pinned the aspect-ratio between 716/720 and 720/716, but I have preserved that. Happy to make more tests if needed, now that I figured out how to build/debug.
=> Retry fixing #1869 (bad display on square screen)

src/ui/shared/round/OnlineRound.ts, src/vibrate.ts
Instead of a generic 'vibrate' game events now emit different haptic effects.
There are different effects for:
- Regular move
- Capture
- Check
- Draw
- Win
- Lose
Fixes: #1918
Caveat: 
I have very little idea what I'm doing here. Haven't used capacitor before and it's been quite a while since I touched mobile dev.
Seems to work as expected though, both in "play against computer" and online play.
=> Make game events emit haptic effects

src/styl/game.styl
Fixes #2074.
Promo pieces are currently scaled to 60x60px, which gets too big when the base zoom is scaled up or down, as detailed in the linked issue.
To make the promo overlay pieces the same size as the pieces on the board, this PR essentially aims to change the promo piece height and width to 12.5% of the overlay (and screen) width. It will consequently often match the board piece width, and is in any case reasonably legible.
In order to actually match the height to 12.5% of width, I had to write a CSS hack, as indicated by a comment. I also capped the piece width/height at 100% of the overlay height in order to keep the pieces within the overlay bounds in edge-case font/screen configurations.
Lastly, I took the liberty of making the promo overlay a flex component. This might not have …
=> Scale promo piece size relative to screen width

android/app/src/main/res/drawable/ic_launcher_monochrome.xml, android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Add a monochrome vector drawable in ic_launcher_round.xml in order to
support Android 13's Themed Icons feature in the launcher.
Preview: 
Signed-off-by: Gegham Zakaryan <zakaryan.2004@outlook.com>
=> android: Monochrome icon for Android 13+

android/app/src/main/AndroidManifest.xml
This ensures that the Android system automatically checks the declared domain (lichess.org) by looking for the file
/.well-known/assetlinks.json and verifying the package name and signature finger print listed there.
More info:
https://developer.android.com/training/app-links/verify-site-associations
Fixes #1457, with the help of (already deployed [lila#11062](https://github.com/lichess-org/lila/pull/11062))
=> Domain verification: app portion

src/styl/clock.styl, src/ui/clock/ChessClockCtrl.ts, src/ui/clock/clockView.tsx
I've added a counter that counts how many moves have been made , as described in the issue #2024 and added a new element to the chess clock UI.
Portrait mode:
Landscape mode:
=> Added current number of move to the chess clock ui #2024

src/styl/game.styl, src/ui/shared/round/view/roundView.tsx
Should fix #2178.
When a player's material advantage takes more than the available screen space to display, it currently wraps, which displaces the board:
Material advantage row is height-restricted to exactly one piece. Advantage number is never hidden, but individual piece representations are hidden when necessary.
Does not affect screens of sufficient width.
=> Prevent overflow of material advantage display

.github/actions/build-lichobile-apk/action.yml, .github/workflows/android.yml, README.md, android/app/build.gradle, android/build.gradle, package.json, scripts/patch-nonfree.js, src/push.stub.ts, src/push.ts, src/ui/settings/settings.ts, src/ui/settings/soundNotifications.ts
**Disclaimer:** This is a proposal more than anything else. I think the added maintenance burden is rather minimal, but if you think otherwise that's OK. I can as well maintain my own fork with these changes. Feel free to close. No pressure, no nothing 🙂 .
Also, as I said in [this comment](https://github.com/lichess-org/lichobile/issues/1121#issuecomment-1190883854), I think the push stub is pretty equivalent to having the "Notifications" checkbox disabled in the current Play Store version which sounds quite harmless. But I'm still not 100% sure `pushNotificationActionPerformed` hook cannot be invoked when not registered.
Also, I was able to build the debug version without issue, but the release version won't build on my machine at the moment, even on master branch with the following …
=> Allow building without firebase-messaging.

android/app/build.gradle
It was deprecated a while ago because of JCenter shutdown. And F-Droid scanner complains about it.
See:
- https://github.com/ionic-team/capacitor/discussions/4542#discussioncomment-707978
- https://github.com/lichess-org/lichobile/issues/1121#issuecomment-1239735238
=> remove deprecated ionic maven repository

COPYING.md
Correct me if I'm wrong, but it seems that this project is no longer sending data to Sentry, despite what's claimed in the COPYING file. So this PR just removes the mention to Sentry.
Probably removed somewhere around here : e2274bb85c4b9062856603e73318f83394754f71 fc31285342b4d56fd86d3445cf4c576ad84a803f
See also: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11707/diffs#note_1095861444
=> remove Sentry from external services

src/styl/game.styl
Old Android WebView versions might not support [calc](https://caniuse.com/calc) or [math](https://caniuse.com/css-math-functions) functions properly, if at all, which makes the promo menu appear empty.
To solve this, either the user needs to update their WebView to the latest version or we can add fallback values as a catchall.
These are the tests I've done on my Android 8.1 device :
* WebView 70 + 1.7.16 release -> Empty Menu
* WebView 70 + 1.7.16 release (with fallbacks) -> Correct Menu
* WebView 104 + 1.7.16 release -> Correct Menu
I don't know if this fully fixes the empty menu issue, but for my device it appears to be the case.
=> Add fallback values for promo menu

src/lichess/interfaces/game.ts, src/ui/tournament/detail/tournamentView.tsx, www/data/positions.json
In https://github.com/lichess-org/lila/commit/4069e5cda6d58f4a7bdb6c68e93529b58592beda#diff-af31ce017b5b4a92ea00b1a33043e014c674e621a5709d4ff425e54c5b6383dfL587
It now contains a link to the https://lichess.org/opening entry.
=> Tournament wikiPath has been replaced with url
