lichess-org/lichobile

project/src/js/i18n.js, project/src/js/main.js, project/src/js/ui/gamesMenu.js, project/src/js/ui/menu.js, project/src/js/ui/otb/data.js, project/src/js/ui/otb/ground.js, project/src/js/ui/otb/main.js, project/src/js/ui/otb/otbCtrl.js, project/src/js/ui/otb/otbView.js, project/src/js/ui/otb/promotion.js, project/src/js/ui/otb/replay/replayCtrl.js, project/src/js/ui/otb/replay/replayView.js, project/src/js/ui/round/view/roundView.js
Where people can play locally on a single device
=> New game mode: OTB

project/src/js/ui/gamesMenu.js, project/src/js/ui/loginModal.js, project/src/js/ui/menu.js, project/src/js/ui/round/chat.js, project/src/js/ui/round/view/roundView.js, project/src/js/utils.js, project/src/styl/game.styl, project/src/styl/menu.styl, project/src/styl/modal.styl, project/src/styl/overlay.styl
with the exception of the left menu.
=> Only produce virtual dom for what's visible on screen

project/src/js/i18n.js, project/src/js/xhr.js
It's disruptive, and apps upgrade automatically anyway
=> Stop warning users about new versions

project/package.json
fixing https://github.com/peutetre/mobile-button/issues/24
=> bump mobile-button to 0.8.1

project/src/styl/game.styl
=> make player rating font a tad bit larger

project/src/js/ui/round/view/roundView.js
I'd like to have this, too. Here we go.
=> Add computer tv channel (closes #203)

project/src/js/ui/shared/offlineRound/replayCtrl.js
See https://github.com/veloce/lichobile/issues/232
=> remove faulty PGN tag - fixes #232

project/src/js/ui/tournament/detail/tournamentDetailView.js
Issue: Link associated with featured game did not change when feature game changed.
Fix: Add a key to tournamentMiniBoard <div> to fix the issue.
=> Feature Game Bug Fix

project/src/js/ui/tournament/detail/tournamentDetailCtrl.js, project/src/js/ui/tournament/detail/tournamentDetailView.js, project/src/js/ui/tournament/tournamentXhr.js, project/src/styl/tournament.styl
Also add stripe to left of user's name in leader board.
=> Add Navigation Buttons to Leader Board

project/src/js/ui/round/promotion.js, project/src/js/ui/shared/offlineRound/promotion.js
Closes https://github.com/veloce/lichobile/issues/379
=> Fix Antichess promotion in analysis view

project/src/js/settings.ts, project/src/js/ui/clock/clockCtrl.js, project/src/js/ui/clock/clockSettings.js, project/src/styl/clock.styl
Add an increment clock with different time and increment (i.e., handicap) for top and bottom players
=> Handicap Increment Clock

project/src/js/ui/clock/clockCtrl.js, project/src/js/ui/clock/clockSettings.js, project/src/js/ui/clock/clockView.js, project/src/styl/clock.styl
Dim clock on pause and don't show play-pause button after flag or before game start
=> Play-pause Tweaks

project/src/js/session.ts, project/src/js/ui/shared/round/OnlineRound.ts, project/src/js/ui/shared/round/chat.js
UNTESTED code, very probably it doesn't work.
=> chat: handle shadowban, deleted messages, anti-spam - fixes #431

project/src/js/ui/clock/clockView.js, project/src/js/ui/clock/clocks/StageClock.js
Closes https://github.com/veloce/lichobile/issues/463
=> Fix stage clock

src/js/ui/loginModal.ts, src/styl/login.styl
Closes https://github.com/veloce/lichobile/issues/471
=> Add link to password reset webpage and adjust styling of registration link

src/js/push.js
Closes https://github.com/veloce/lichobile/issues/236
=> Handle 'corresAlarm' push notifications for correspondence players who are low on time

src/js/ui/shared/round/view/roundView.jsx, src/js/ui/shared/round/view/roundView.tsx
Closes https://github.com/veloce/lichobile/issues/452
=> Fix tournament move warning when spectator

src/dts/lichess.d.ts, src/js/ui/shared/round/OnlineRound.ts, src/js/ui/shared/round/chat.js, src/js/ui/shared/round/socketHandler.ts, src/styl/chat.styl
Closes https://github.com/veloce/lichobile/issues/372
Also Closes https://github.com/veloce/lichobile/issues/468
=> Add spectator chat

src/js/ui/analyse/explorer/explorerCtrl.ts
Now that #491 is prepared, enabling atomic tablebases is trivial.
=> Enable atomic tablebase

src/js/ui/user/followers/followersCtrl.js, src/js/ui/user/followers/followersView.js, src/js/ui/user/following/followingCtrl.js, src/js/ui/user/following/followingView.js, src/styl/user.styl
Closes https://github.com/veloce/lichobile/issues/389
=> Pagination for Follwers/Following Pages

www/data/endgames.json
Many beginner and some intermediate/advanced positions were added.  Reordered the positions in terms of what level they should be mastered, based on the book, "Silman's Complete Endgame Course".  Renamed the positions to better highlight the contents (no more basic endgames), and to correct some roman numerals.
=> Add, reorder, and rename positions

src/js/ui/inbox/compose/composeView.tsx, src/js/ui/inbox/compose/index.ts, src/js/ui/inbox/inboxXhr.ts, src/js/ui/inbox/interfaces.ts
Closes https://github.com/veloce/lichobile/issues/550
=> Add auto complete to recipient field in composeView

src/js/ui/training/menu.js
=> training: include current rating in graph

src/js/ui/shared/round/OnlineRound.ts, www/lib/socketWorker.js
- Send lag in pongs with same logic as website
- Don't bother with lag millis if sending move time.
- Use improved formula for calculating average lag.
=> Update lag protocol for app

src/js/lichess/interfaces/move.ts, src/js/ui/shared/round/OnlineRound.ts, src/js/ui/shared/round/clock/ClockCtrl.ts
- Reset move timer on reload
- Send lag values while clocks are paused
- Use lag value for delay
This fixes #647.
=> Clock improvements

src/ui/menu/menuView.tsx
Fixes #717
Signed-off-by: TheCodeArtist <cvs268@gmail.com>
=> Open the user profile page upon clicking username

src/ui/analyse/AnalyseCtrl.ts, src/ui/analyse/analyseSocketHandler.ts
=> Fix analysis completed detection

src/lichess/interfaces/tournament.ts, src/styl/custom_theme.styl, src/styl/tournament.styl, src/ui/tournament/detail/tournamentView.tsx
Addresses https://github.com/veloce/lichobile/issues/720
=> Add spotlight info, refactor tournament header for readability and make a couple style tweaks

config.xml, src/deepLinks.ts
@ornicar learned from a user that opening a link like `lichess.org/@/freefal/tv` in the app will just open the user profile page for the user named `tv`.
This fixes that issue.
=> Fix User TV

src/ui/inbox/thread/threadView.tsx, src/utils/html.ts, src/utils/index.ts
Closes https://github.com/veloce/lichobile/issues/739
Links are <a> tags with the target set to `_system`. The user then has to confirm that they wish to open the link in the app. Once they do, the link falls through all the same deep links logic we've already established.
=> Linkify Private Messages

src/styl/game.styl
Addresses this issue https://github.com/veloce/lichobile/issues/752
=> Conform formatting of threefold repetition button

src/utils/html.ts
Untested 😨 
Similar to https://github.com/ornicar/lila/commit/36d70d9c29dd839f7965d04fc7eea471a6c6f6b5
=> Allow "@" in URLs for auto linking

src/ui/user/games/gamesView.tsx
rather than the analysis board for that game
=> Clicking on a game in a player's game list that is live should route the user to that game

COPYING.md, LICENSE
Two weeks ago we asked all contributors about the relicensing (#771, with a reminder via e-mail). The decision is unanimous with a couple pending responses.
Fortunately we do not have to wait for everyone: We asked regardless of the type of contribution. For example fixing typos is very useful, but does not reach a threshold of originality. So we can move forward now.
=> Relicense under the GPL 3

src/lichess/interfaces/training.ts, src/styl/training.styl, src/ui/training/TrainingCtrl.ts, src/ui/training/interfaces.ts, src/ui/training/trainingView.ts, src/ui/training/xhr.ts
Added vote count and ability to vote at the end of puzzles.
This fixes #660.
The functionality is correct, but it doesn't look too good - I couldn't make it align to the right.
I would really appreciate some help with the styling part.
=> Training: Add votes to puzzles

src/chessground/Chessground.ts, src/chessground/interfaces.ts, src/styl/game.styl, src/ui/shared/round/index.ts, src/ui/shared/round/view/roundView.tsx
Hi,
I added the little score next to the piece cemetery like in the lichess website.
I again have some problems with the styling, the number is a bit lower than the pieces. The margin-top that I placed on the score seems to no work like it does on the piece.
=> Add score to the piece cemetery

src/routes.ts, src/styl/about.styl, src/ui/about/index.tsx, src/ui/helper/index.ts, src/ui/menu/menuView.tsx
It probably makes sense to add a paragraph on the history of the mobile app, but I wasn't around so can't author it.
=> Add about page

COPYING.md
Add it to the list of exceptions
=> Companion is non-free

src/ui/analyse/explorer/ExplorerCtrl.ts
Following ornicar/lila@7f478bae82717f8c66a7b557e802327d20ebaabc.
=> Future proof for 7-man endgame tablebases

src/ui/tournament/detail/tournamentView.tsx
Fix error in which all tournament players appeared to be on fire.
It appears this was broken a couple months ago here (https://github.com/veloce/lichobile/commit/9d5ffd068a18950b8e43b20de0bb42f07a25e675)
=> Fix Tournament Fire Error

src/styl/tournament.styl, src/ui/tournament/newTournamentForm.tsx, src/ui/tournament/tournamentXhr.ts
Closes https://github.com/veloce/lichobile/issues/883
=> Allow users to name their tournaments

src/ui/analyse/AnalyseCtrl.ts, src/ui/analyse/index.ts, src/ui/analyse/study/StudyCtrl.ts, src/ui/study/study/index.ts, src/ui/study/study/view/RightSideMenu.ts
Closes https://github.com/veloce/lichobile/issues/886
=> Remember tab when switching between study chapters

src/dts/lichess.d.ts, src/lichess/game.ts, src/main.ts, src/socket.ts, src/ui/menu/index.ts, src/ui/shared/round/OnlineRound.ts, www/lib/socketWorker.js
Addresses issue raised here (https://github.com/veloce/lichobile/issues/928) by flagging moves made after app resume.
Also fixes some lint errors.
=> Add flag denoting that the app has been resumed and report it to Lila to aid cheat detection

src/ui/study/studyListView.ts
Spotted a typo in the app, glad I could help in a trivial way!
=> Correct a typo

src/deepLinks.ts
Fixes this issue: https://github.com/veloce/lichobile/issues/956
=> Process variant if present before fen in analysis link

README.md
Tiny fix in the README: lib++ -> libc++.
=> Fix in the README: lib++ -> libc++

src/ui/shared/GameItem.tsx
Closes https://github.com/veloce/lichobile/issues/1067
=> Fix GameItem so that it correctly shows the names of players in imported games

src/ui/analyse/index.ts, src/ui/training/TrainingCtrl.ts
Closes: https://github.com/veloce/lichobile/issues/1063
=> Gracefully fallback to offline analysis of a puzzle if fetching the game for online analysis fails

src/i18n.ts, src/ui/home/homeView.tsx, src/ui/menu/menuView.tsx, src/ui/study/studyListView.ts
Applied i18n to strings that are already translated in the lichess project, but were not in use here.
=> Some i18n cleanup

src/settings.ts, src/styl/chessground-piece.styl, src/styl/settings.styl, www/images/pieces/pixel/bB.svg, www/images/pieces/pixel/bK.svg, www/images/pieces/pixel/bN.svg, www/images/pieces/pixel/bP.svg, www/images/pieces/pixel/bQ.svg, www/images/pieces/pixel/bR.svg, www/images/pieces/pixel/wB.svg, www/images/pieces/pixel/wK.svg, www/images/pieces/pixel/wN.svg, www/images/pieces/pixel/wP.svg, www/images/pieces/pixel/wQ.svg, www/images/pieces/pixel/wR.svg
Would love to have these pixel pieces added to the mobile app!
=> Added 'pixel' piece set from lichess site. 

src/styl/clock.styl, src/ui/clock/clockView.tsx
This implements the proposed feature request #1215.
=> Make clock display milliseconds when low on time( < 60secs ).

COPYING.md, src/settings.ts, src/styl/chessground-piece.styl, src/styl/settings.styl, www/images/pieces/cardinal/bB.svg, www/images/pieces/cardinal/bK.svg, www/images/pieces/cardinal/bN.svg, www/images/pieces/cardinal/bP.svg, www/images/pieces/cardinal/bQ.svg, www/images/pieces/cardinal/bR.svg, www/images/pieces/cardinal/wB.svg, www/images/pieces/cardinal/wK.svg, www/images/pieces/cardinal/wN.svg, www/images/pieces/cardinal/wP.svg, www/images/pieces/cardinal/wQ.svg, www/images/pieces/cardinal/wR.svg
This adds the missing cardinal piece set as requested in #1231.
=> Added 'cardinal' piece set from lichess site.

README.md
Because you can never have too many badges
=> Added more badges.

src/styl/challenge.styl, src/ui/game/challengeView.tsx
Closes #932.
This adds a small clipboard icon over the input box, see below:
=> Copy challenge URL to clipboard on tap

src/ui/analyse/contextMenu.ts
=> i18n: "Delete from here"

jest.config.js, src/__tests__/http.ts, src/index.mustache, src/ui/training/training.ts, src/utils/__tests__/util.ts, src/utils/index.ts, tsconfig.test.json
=> Convert base62 training IDs to numbers if necessary

.eslintrc.js, src/ui/analyse/forecast/ForecastCtrl.ts, src/ui/analyse/forecast/forecastView.ts, src/ui/helper/Siema.js, src/ui/helper/button.ts, src/ui/shared/round/__tests__/backoff.test.ts, src/utils/lru/index.d.ts, src/utils/lru/index.js, src/utils/zanimo/index.js
Spun off from https://github.com/veloce/lichobile/pull/1520#pullrequestreview-585029716.
=> Lint: disallow semicolons

src/ui/training/TrainingCtrl.ts, src/ui/training/trainingView.ts
As the server [doesn't send the "check" property](https://github.com/ornicar/lila/blob/a075a5f105e2333916e3f28e0b39aa52e5520170/modules/puzzle/src/main/GameJson.scala#L111-L115), we need to infer it from the first move SAN. Closes #1597.
=> Fix first move check aura not appearing in puzzles

crowdin.yml, scripts/i18n-update.ts, translation/source/mobile-misc.json
🌍  🌎  🌏 
This PR sets up configuration such that this repo can be added to the lichess CrowdIn project.
Once this PR is merged, a CrowdIn administrator can add this repo, selecting the master branch as the source branch and maybe `i18n-master` (or whatever name they want) as the dest branch. Then, any changes in JSON files in `translation/source/*.json` will be automatically imported into the CrowdIn project.
As strings are translated, CrowdIn will automatically commit changes into `translation/dest/<locale>/<filename>.json` on the `i18n-master` branch. When we're ready to bring said translations back into the master branch, we can create a merge PR.
Then, we run `npm run i18n-update`. This will download and unpack requested lila translation modules as before, but this time it will also …
=> Set up repository for CrowdIn

src/ui/shared/round/OnlineRound.ts, src/ui/shared/round/view/button.tsx
Closes #1593.
https://user-images.githubusercontent.com/569991/112079165-10309600-8b56-11eb-93c9-921e58c73cef.mov
=> Cancel premove when accepting a takeback

crowdin.yaml, scripts/i18n-update.ts, scripts/package-lock.json, scripts/package.json, translation/source/mobile-misc.json, translation/source/mobile-misc.yaml
Follow-up from https://github.com/veloce/lichobile/pull/1601/files#r598340314 : we may need pluralization in the future, which is not well-supported in JSON sources.
=> Change i18n source format to YAML

src/ui/clock/clockView.tsx
Came across https://github.com/veloce/lichobile/issues/634 and thought it's weird that you have no info of the stage you're at.
The guidelines say that `npm run build-stage` must pass before opening a PR, but that task is not defined.
I've ensured that `npm run lint` and `npm run test` pass, though.
It's my first contribution to an open source project ever, so please tell me if I screw up somewhere :)
=> Clock Tool: added stage count

src/ui/settings/gameDisplay.ts
This just uses the i18n keys created in #1622 to i18n the new feature from #1633.
=> i18n board side preference

src/lichess/interfaces/index.ts, src/lichess/interfaces/user.ts, src/ui/shared/PlayerPopup.tsx, src/xhr.ts
Verified locally using a connection to the production servers by opening the player popup for one user I had played at least one game with, and one user I hadn't.
=> Add some types and one i18n cleanup

src/lichess/interfaces/user.ts, src/session.ts, src/ui/shared/PlayerPopup.tsx, src/ui/shared/round/view/roundView.tsx, src/ui/user/userView.tsx
I could not test these changes since I do not have a mobile env.
I didn't remove the i18n key `thisPlayerArtificiallyIncreasesTheirRating` since I assume will be erased by next crowdin dump.
=> remove `booster` field

src/ui/coordinates/CoordCtrl.ts, src/ui/coordinates/coordView.ts, www/i18n/en-US.js, www/i18n/es-ES.js
Added simple functionality and two translations, more translations will be needed.
=> #1691 - added functionality desired for previous score shown in coordinate training

deepLinkTest.html, src/deepLinks.ts, src/ui/game/game.ts, src/ui/shared/round/OnlineRound.ts
=> Deep link to game ply

src/lichess/game.ts, src/ui/shared/round/view/button.tsx, src/webPlugins.ts
Closes #1705 . Tested locally.
=> Add orientation to game share URL

.github/workflows/build.yml, .github/workflows/checks.yml, package.json
https://docs.npmjs.com/cli/v7/commands/npm-ci
=> Fix GitHub CI

src/lichess/interfaces/index.ts, src/lichess/interfaces/tournament.ts, src/ui/home/HomeCtrl.ts, src/ui/home/homeView.tsx, src/ui/tournament/tournamentsListView.tsx
=> Fix tournament and correspondence seek list icons

src/ui/shared/round/view/button.tsx
=> Add current ply to game share URI

src/lichess/game.ts, src/ui/analyse/menu.ts, www/i18n/en-US.js
From analyse control, like the website. Closes #1162. It's only the GIF URL, not the GIF data itself, but the latter would require a lot more effort.
=> Add button to share game GIF

src/ui/shared/chat.ts
A SB player must not see lines of other SB players, only their own
=> fix chat mute between SB players

src/ui/loginModal.ts, src/ui/signupModal.ts
Hello, as I mentioned in #1806 I wanted to make these small changes to improve the UX while logging in or signing up via the lichess app.
I decided to not trim the password fields since mobile keyboards disable auto completion in password fields.
=> Trim input values in login and signup forms

src/ui/shared/PlayerPopup.tsx, src/ui/user/userView.tsx
minor cleanup after ornicar/lila#9514. field was always optional, and is now gone.
=> remove language from profiles following ornicar/lila#9514

src/lichess/interfaces/user.ts, src/styl/players.styl, src/ui/players/PlayersCtrl.ts, src/ui/players/playerXhr.ts, src/ui/players/playersView.tsx
Closes #1816.
https://user-images.githubusercontent.com/569991/130381078-daf46288-03dd-416f-98d2-9c7006c9fc2e.mov
=> Player search decorations

.eslintrc.json, src/lichess/interfaces/tournament.ts, src/ui/tournament/detail/tournamentView.tsx
Closes #1814. Compare screenshot to the one in the issue.
=> Tournament player titles

src/lichess/interfaces/analyse.ts, src/styl/gameAnalysis.styl, src/ui/analyse/charts/acpl.ts, src/ui/analyse/charts/moveTimes.ts
=> i18n chart game stage indicator text

src/ui/tournament/newTournamentForm.tsx
=> i18n some tournament options

src/ui/analyse/explorer/explorerConfig.ts, src/ui/analyse/explorer/explorerXhr.ts
Update to the new opening explorer API. Does not add any of the new features (date ranges, ultra bullet, correspondence, personal opening explorer, more game details).
=> Update explorerXhr to v3

src/styl/study.styl
Closes #1935. Blame for this line dates to May 2018 in d3a4bf7604d43c9a38ddca14ad050076adc3c255
=> Expand comment flexbox height to 100%

src/ui/analyse/ceval/CevalCtrl.ts
=> Restart evaluation when options change

src/lichess/interfaces/tournament.ts, src/ui/tournament/detail/TournamentCtrl.ts, src/ui/tournament/detail/playerInfo.tsx, src/ui/tournament/detail/tournamentView.tsx, src/ui/tournament/tournamentXhr.ts, src/utils/throttle.ts
Fixes tournament updates and makes them easier on the server.
=> Tournament fixes

src/lichess/interfaces/tournament.ts
=> tournament me.withdraw is omitted when false

src/lichess/interfaces/tournament.ts
=> remove unused tournament player.sheet.total from types

src/ui/menu/menuView.tsx
Closes #1986. Tested locally on simulators.
=> Dynamic ping help i18n

src/ui/analyse/study/view.ts, src/ui/analyse/view/richTextView.ts, src/ui/analyse/view/treeView.ts
=> Render newlines as HTML line breaks

src/sound.ts, src/ui/settings/soundNotifications.ts
=> Don't play sounds while in background

src/ui/user/userView.tsx
=> Add friends icon on profile page

src/lichess/interfaces/tournament.ts, src/ui/tournament/detail/playerInfo.tsx
=> Compute arena score colors

src/styl/overlay-popup.styl, src/ui/analyse/AnalyseCtrl.ts, src/ui/analyse/ceval/CevalCtrl.ts, src/ui/analyse/ceval/cevalView.tsx, src/ui/analyse/ceval/interfaces.ts, src/ui/analyse/menu.ts, src/ui/analyse/util.ts, src/ui/analyse/view/boardView.ts, src/ui/shared/BoardBrush/brushes.ts
=> Threat mode

src/ui/analyse/ceval/StockfishClient.ts
=> Fix wrong eval being displayed with multi lines

android/app/capacitor.build.gradle, android/app/src/main/assets/capacitor.plugins.json, android/capacitor.settings.gradle, package-lock.json, package.json, src/app.ts, src/dts/lichess.d.ts, src/settings.ts, src/styl/settings.styl, src/theme.ts, src/ui/layout.ts, src/ui/settings/background.ts, translation/source/mobile-misc.yaml, www/i18n/en-GB.js
In order to benefit from automatic theme switch based on time of the day.
=> Sync background theme with system preferences

src/styl/board-content.styl
=> Fix board aspect for square screens

src/lichess/interfaces/game.ts, src/styl/game.styl, src/ui/analyse/AnalyseCtrl.ts, src/ui/analyse/util.ts, src/ui/shared/round/util.ts, src/ui/shared/round/view/roundView.tsx, src/utils/fen.ts
=> Fix number of checks when rewinding game

src/styl/game.styl, src/ui/shared/round/correspondenceClock/corresClockView.ts, src/ui/shared/round/view/roundView.tsx
=> Fix flipped clocks

src/router.ts, src/ui/ai/AiRound.ts, src/ui/otb/OtbRound.ts, src/ui/otb/importGamePopup.ts, src/ui/shared/offlineRound/index.ts, src/ui/shared/offlineRound/view.tsx, src/ui/shared/round/index.ts
=> Fix canceling new game after editing board

src/ui/players/playerXhr.ts
=> Populate user online status from /player/online

README.md
Hi,
This small PR adds two buttons to get your app on F-Droid and Google Play, and a link to get the app from the Releases section as well 👍 
You can now eventually add the [fdroid](https://github.com/topics/fdroid) and/or [f-droid](https://github.com/topics/f-droid) tags that will appear on the right side of the repo.
=> Update README.md with links to download the APK

src/xhr.ts
See https://github.com/lichess-org/lila/pull/11879.
=> Restore timeline by including `nb` query param

README.md
=> Add repo deprecation notice to README
